# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentLogIn.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 441))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLineEdit.setPlaceholderText("Full Name")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.rollNoLineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.rollNoLineEdit_4.setObjectName("rollNoLineEdit_4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rollNoLineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.branchComboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.branchComboBox_2.setObjectName("branchComboBox_2")
        self.branchComboBox_2.addItem("")
        self.branchComboBox_2.addItem("")
        self.branchComboBox_2.addItem("")
        self.branchComboBox_2.addItem("")
        self.branchComboBox_2.addItem("")
        self.branchComboBox_2.addItem("")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.branchComboBox_2)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dobDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dobDateEdit.setCalendarPopup(True)
        self.dobDateEdit.setObjectName("dobDateEdit")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dobDateEdit)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.contactLineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.contactLineEdit_5.setObjectName("contactLineEdit_5")
#        self.contactLineEdit_5.setValidator(QDoubleValidator(0.99, 99.99, 2))  
        self.contactLineEdit_5.setMaxLength(4)
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.contactLineEdit_5)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.emailLineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.emailLineEdit_6.setObjectName("emailLineEdit_6")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit_6)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.passwordLineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.passwordLineEdit_7.setObjectName("passwordLineEdit_7")
        self.passwordLineEdit_7.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_7)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.genderComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.verticalLayout_5.addLayout(self.formLayout_5)
        self.registerPushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.registerPushButton_2.setObjectName("registerPushButton_2")
        self.verticalLayout_5.addWidget(self.registerPushButton_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.sidLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sidLineEdit_2.setObjectName("sidLineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sidLineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.passwordLineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.passwordLineEdit_3.setObjectName("passwordLineEdit_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_3)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.loginPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.loginPushButton.setObjectName("loginPushButton")
        self.verticalLayout_2.addWidget(self.loginPushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 5)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAkhilesh = QtWidgets.QAction(MainWindow)
        self.actionAkhilesh.setObjectName("actionAkhilesh")
        self.actionAtul = QtWidgets.QAction(MainWindow)
        self.actionAtul.setObjectName("actionAtul")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "RollNo"))
        self.label_5.setText(_translate("MainWindow", "Gender"))
        self.label_6.setText(_translate("MainWindow", "Branch"))
        self.branchComboBox_2.setItemText(0, _translate("MainWindow", "Select Branch"))
        self.branchComboBox_2.setItemText(1, _translate("MainWindow", "CSE"))
        self.branchComboBox_2.setItemText(2, _translate("MainWindow", "ECE"))
        self.branchComboBox_2.setItemText(3, _translate("MainWindow", "EEE"))
        self.branchComboBox_2.setItemText(4, _translate("MainWindow", "MECH"))
        self.branchComboBox_2.setItemText(5, _translate("MainWindow", "CHEM"))
        self.label_7.setText(_translate("MainWindow", "DOB"))
        self.label_8.setText(_translate("MainWindow", "Contact"))
        self.label_9.setText(_translate("MainWindow", "Email"))
        self.label_10.setText(_translate("MainWindow", "Password"))
        self.label_11.setText(_translate("MainWindow", "First Time?"))
        self.genderComboBox.setItemText(0, _translate("MainWindow", "Select Gender"))
        self.genderComboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.genderComboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.genderComboBox.setItemText(3, _translate("MainWindow", "Other"))
        self.registerPushButton_2.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "Frequently Here?"))
        self.label_3.setText(_translate("MainWindow", "SID / RollNo"))
        self.label_12.setText(_translate("MainWindow", "Password"))
        self.loginPushButton.setText(_translate("MainWindow", "LogIn"))
        self.actionAkhilesh.setText(_translate("MainWindow", "akhilesh"))
        self.actionAtul.setText(_translate("MainWindow", "atul"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

